name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout devcontainers/features
      uses: actions/checkout@v3
      with:
        repository: devcontainers/features
        path: features
      
    - name: Update
      run: |
        echo "$(pwd)/main/.github/bin" >> $GITHUB_PATH
        sync-feature php

    - name: Modify
      run: |
        echo "$(pwd)/main/.github/bin" >> $GITHUB_PATH
        cd main/src/php
        remove-extension "devsense.phptools-vscode"
        remove-extension "xdebug.php-pack"
        add-extension    "devsense.phptools-vscode"

    - name: Check
      run: |
        cat main/src/php/devcontainer-feature.json

    - name: Commit
      run: |
        cd main
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Automated update"
           
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        directory: main
