name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository
      uses: actions/checkout@v3
      with:
        path: devcontainer-features
      
    - name: Pull offical features
      uses: actions/checkout@v3
      with:
        name: devcontainers/features
        path: features
      
    - name: Update php feature
      run:  |
        echo "Root contents:"
        ls -l
        echo "Offical contents:"
        cd features
        ls -l 
        echo "Custom contents:"
        cd ../devcontainer-features
        ls -l
        echo "Updating..."
        cp -r offical/src/php custom/
           
    - name: Check
      run: ls -l custom/
