name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout devcontainers/features
      uses: actions/checkout@v3
      with:
        repository: devcontainers/features
        path: features
      
    - name: Check
      run:  |
        echo "Root contents:"
        ls -l
        echo "Offical contents:"
        ls -l main
        echo "Custom contents:"
        ls -l devcontainer-features
        echo "Updating..."
